name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake configure
      run: cmake -B ./build
    - name: cmake build
      run: cmake --build ./build -j4 --config Debug
    - name: cmake test
      run: cd ./build && ctest
